#!/bin/bash

IMAGE_NAME=danos-2005-base

function import_source() {
    if [[ -n $DANOS_SRC_MOUNTED ]]; then
	cp -a /mnt/src $IMAGE_NAME
    else
	wget -O- -q https://s3-us-west-1.amazonaws.com/repos.danosproject.org/2005/livebuild/danos-2005-base-Build2.4.livebuild.tar | tar xv
    fi

    pushd $IMAGE_NAME
    mkdir -p config/archives/
    echo 'deb http://repos.danosproject.org.s3-website-us-west-1.amazonaws.com/repo/ 2005 main' > config/archives/standard.list.chroot
    wget https://s3-us-west-1.amazonaws.com/repos.danosproject.org/Release.key -O config/archives/repo.key.chroot
    popd
}

function import_preferred_packages() {
    mkdir -p $IMAGE_NAME/config/packages.chroot/
    cp /mnt/pkgs/*.deb $IMAGE_NAME/config/packages.chroot/
}

function build_image() {
    pushd $IMAGE_NAME
    auto/config
    auto/build
    popd
}

function export_image() {
    echo "exporting images... this may take a while"
    cp $IMAGE_NAME/$IMAGE_NAME* /mnt/output
}

function workaround_919659() {
    # Workaround https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=919659
    sed -i '1161s%umount%#umount%' /usr/share/debootstrap/functions
}

workaround_919659 || exit 1
import_source || exit 1
import_preferred_packages
build_image || exit 1
export_image || exit 1
