#!/bin/bash

IMAGE_NAME=danos-2009-base

function import_source() {
    if [[ -n $DANOS_SRC_MOUNTED ]]; then
	cp -a /mnt/src $IMAGE_NAME
    else
	wget -O- -q https://s3-us-west-1.amazonaws.com/2009.repos.danosproject.org/2009/livebuild/danos-2009-base.livebuild.tar | tar xv
    fi

    pushd $IMAGE_NAME
    mkdir -p config/archives/
    echo 'deb http://s3-us-west-1.amazonaws.com/2009.repos.danosproject.org/repo/ 2009 main' > config/archives/danos.list.chroot
    echo -e 'Package: *\nPin: release o=DANOS\nPin-Priority: 1000' > config/archives/danos.pref.chroot
    wget https://s3-us-west-1.amazonaws.com/repos.danosproject.org/Release.key -O config/archives/danos.key.chroot
    popd
}

function import_preferred_packages() {
    mkdir -p $IMAGE_NAME/config/packages.chroot/
    cp /mnt/pkgs/*.deb $IMAGE_NAME/config/packages.chroot/
}

function customize_apt() {
    pushd $IMAGE_NAME
    sed -i 's/--yes/--yes --force-yes/' auto/config
    popd
}

function build_image() {
    pushd $IMAGE_NAME
    auto/config
    auto/build
    popd
}

function export_image() {
    echo "exporting images... this may take a while"
    cp $IMAGE_NAME/$IMAGE_NAME* /mnt/output
}

function workaround_919659() {
    # Workaround https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=919659
    sed -i '1161s%umount%#umount%' /usr/share/debootstrap/functions
}

workaround_919659 || exit 1
import_source || exit 1
import_preferred_packages
customize_apt || exit 1
build_image || exit 1
export_image || exit 1
